/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check — toujours 200 si l'app tourne.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness check — 503 si la BDD est inaccessible.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Login
         * @description Redirige vers Google OAuth. Origin encodé et signé (HMAC) dans le state CSRF.
         */
        get: operations["google_login_api_v1_auth_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Callback Google OAuth.
         *     - Vérifie la signature CSRF du state
         *     - Échange le code contre les infos utilisateur
         *     - Vérifie le domaine @eleven-labs.com
         *     - Crée l'astronaute si première connexion
         *     - Redirige vers frontend ou backoffice avec le JWT
         *     Note: le JWT est transmis en query param (?token=) — trade-off accepté pour ce flow
         *     de dev (CLAUDE.md §5). Migration vers httpOnly cookie prévue.
         */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Retourne le profil de l'astronaute connecté.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planets */
        get: operations["list_planets_api_v1_planets_get"];
        put?: never;
        /** Create Planet */
        post: operations["create_planet_api_v1_planets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planets/{planet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planet */
        get: operations["get_planet_api_v1_planets__planet_id__get"];
        put?: never;
        post?: never;
        /** Delete Planet */
        delete: operations["delete_planet_api_v1_planets__planet_id__delete"];
        options?: never;
        head?: never;
        /** Update Planet */
        patch: operations["update_planet_api_v1_planets__planet_id__patch"];
        trace?: never;
    };
    "/api/v1/astronauts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Astronauts */
        get: operations["list_astronauts_api_v1_astronauts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/astronauts/{astronaut_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Astronaut */
        get: operations["get_astronaut_api_v1_astronauts__astronaut_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Astronaut Profile
         * @description Met à jour le profil d'un astronaute.
         *     L'astronaute ne peut modifier que son propre profil (photo_url, hobbies, client).
         *     Un admin peut en plus modifier : planet_id, hire_date, first_name, last_name.
         */
        patch: operations["update_astronaut_profile_api_v1_astronauts__astronaut_id__patch"];
        trace?: never;
    };
    "/api/v1/astronauts/{astronaut_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Astronaut Roles
         * @description Met à jour les rôles d'un astronaute (admin uniquement).
         *     Un admin ne peut pas se retirer lui-même le rôle admin.
         */
        patch: operations["update_astronaut_roles_api_v1_astronauts__astronaut_id__roles_patch"];
        trace?: never;
    };
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_v1_seasons_get"];
        put?: never;
        /** Create Season */
        post: operations["create_season_api_v1_seasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Season */
        get: operations["get_active_season_api_v1_seasons_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Season */
        post: operations["activate_season_api_v1_seasons__season_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Season
         * @description Clôture une saison : désactive + reset des compteurs planète.
         */
        post: operations["close_season_api_v1_seasons__season_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_v1_activities_get"];
        put?: never;
        /** Create Activity */
        post: operations["create_activity_api_v1_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_v1_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Activity */
        patch: operations["update_activity_api_v1_activities__activity_id__patch"];
        trace?: never;
    };
    "/api/v1/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grades */
        get: operations["list_grades_api_v1_grades_get"];
        put?: never;
        /** Create Grade */
        post: operations["create_grade_api_v1_grades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grades/{grade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Grade */
        delete: operations["delete_grade_api_v1_grades__grade_id__delete"];
        options?: never;
        head?: never;
        /** Update Grade */
        patch: operations["update_grade_api_v1_grades__grade_id__patch"];
        trace?: never;
    };
    "/api/v1/point-attributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attributions */
        get: operations["list_attributions_api_v1_point_attributions_get"];
        put?: never;
        /** Create Attribution */
        post: operations["create_attribution_api_v1_point_attributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/point-attributions/{attribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Attribution */
        delete: operations["delete_attribution_api_v1_point_attributions__attribution_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityCreate */
        ActivityCreate: {
            /** Name */
            name: string;
            /** Base Points */
            base_points: number;
            /** Category */
            category: string;
            /**
             * Is Collaborative
             * @default false
             */
            is_collaborative: boolean;
            /**
             * Allow Multiple Assignees
             * @default false
             */
            allow_multiple_assignees: boolean;
        };
        /** ActivityOut */
        ActivityOut: {
            /** Name */
            name: string;
            /** Base Points */
            base_points: number;
            /** Category */
            category: string;
            /**
             * Is Collaborative
             * @default false
             */
            is_collaborative: boolean;
            /**
             * Allow Multiple Assignees
             * @default false
             */
            allow_multiple_assignees: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /** ActivityUpdate */
        ActivityUpdate: {
            /** Name */
            name?: string | null;
            /** Base Points */
            base_points?: number | null;
            /** Category */
            category?: string | null;
            /** Is Collaborative */
            is_collaborative?: boolean | null;
            /** Allow Multiple Assignees */
            allow_multiple_assignees?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** AstronautMe */
        AstronautMe: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Roles */
            roles: string[];
            /** Planet Id */
            planet_id: number | null;
            /** Total Points */
            total_points: number;
        };
        /** AstronautOut */
        AstronautOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Hobbies */
            hobbies: string | null;
            /** Client */
            client: string | null;
            /** Hire Date */
            hire_date: string | null;
            /** Planet Id */
            planet_id: number | null;
            /** Roles */
            roles: string[];
            /** Total Points */
            total_points: number;
            /** Grade Name */
            grade_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AstronautPatch
         * @description Body unifié pour PATCH /astronauts/{id}.
         *     Champs self-edit : photo_url, hobbies, client.
         *     Champs admin uniquement : planet_id, hire_date, first_name, last_name.
         */
        AstronautPatch: {
            /** Photo Url */
            photo_url?: string | null;
            /** Hobbies */
            hobbies?: string | null;
            /** Client */
            client?: string | null;
            /** Planet Id */
            planet_id?: number | null;
            /** Hire Date */
            hire_date?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** AstronautRoleUpdate */
        AstronautRoleUpdate: {
            /** Roles */
            roles: string[];
        };
        /** GradeCreate */
        GradeCreate: {
            /** Name */
            name: string;
            /** Threshold Points */
            threshold_points: number;
            /** Order */
            order: number;
        };
        /** GradeOut */
        GradeOut: {
            /** Name */
            name: string;
            /** Threshold Points */
            threshold_points: number;
            /** Order */
            order: number;
            /** Id */
            id: number;
        };
        /** GradeUpdate */
        GradeUpdate: {
            /** Name */
            name?: string | null;
            /** Threshold Points */
            threshold_points?: number | null;
            /** Order */
            order?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanetCreate */
        PlanetCreate: {
            /** Name */
            name: string;
            /** Mantra */
            mantra?: string | null;
            /** Blason Url */
            blason_url?: string | null;
            /** Color Hex */
            color_hex?: string | null;
            /**
             * Is Competing
             * @default true
             */
            is_competing: boolean;
            /**
             * Is Default For Newcomers
             * @default false
             */
            is_default_for_newcomers: boolean;
        };
        /** PlanetOut */
        PlanetOut: {
            /** Name */
            name: string;
            /** Mantra */
            mantra?: string | null;
            /** Blason Url */
            blason_url?: string | null;
            /** Color Hex */
            color_hex?: string | null;
            /**
             * Is Competing
             * @default true
             */
            is_competing: boolean;
            /**
             * Is Default For Newcomers
             * @default false
             */
            is_default_for_newcomers: boolean;
            /** Id */
            id: number;
            /**
             * Season Score
             * @default 0
             */
            season_score: number;
        };
        /** PlanetUpdate */
        PlanetUpdate: {
            /** Name */
            name?: string | null;
            /** Mantra */
            mantra?: string | null;
            /** Blason Url */
            blason_url?: string | null;
            /** Color Hex */
            color_hex?: string | null;
            /** Is Competing */
            is_competing?: boolean | null;
            /** Is Default For Newcomers */
            is_default_for_newcomers?: boolean | null;
        };
        /** PointAttributionCreate */
        PointAttributionCreate: {
            /** Astronaut Ids */
            astronaut_ids: number[];
            /** Activity Id */
            activity_id: number;
            /** Points */
            points?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /** PointAttributionDeleteRequest */
        PointAttributionDeleteRequest: {
            /** Reason */
            reason: string;
        };
        /** PointAttributionOut */
        PointAttributionOut: {
            /** Id */
            id: number;
            /** Astronaut Id */
            astronaut_id: number;
            /** Planet Id */
            planet_id: number;
            /** Activity Id */
            activity_id: number;
            /** Season Id */
            season_id: number;
            /** Awarded By */
            awarded_by: number;
            /** Points */
            points: number;
            /** Comment */
            comment: string | null;
            /** First Ever Multiplier Applied */
            first_ever_multiplier_applied: boolean;
            /** First Season Bonus Applied */
            first_season_bonus_applied: boolean;
            /**
             * Awarded At
             * Format: date-time
             */
            awarded_at: string;
            /** Activity Name */
            activity_name?: string | null;
            /** Astronaut First Name */
            astronaut_first_name?: string | null;
            /** Astronaut Last Name */
            astronaut_last_name?: string | null;
        };
        /** SeasonCreate */
        SeasonCreate: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** SeasonOut */
        SeasonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    google_login_api_v1_auth_google_get: {
        parameters: {
            query?: {
                /** @description 'frontend' ou 'backoffice' */
                origin?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query: {
                /** @description Code OAuth retourné par Google */
                code: string;
                /** @description State CSRF signé (HMAC) */
                state: string;
            };
            header?: {
                accept?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstronautMe"];
                };
            };
        };
    };
    list_planets_api_v1_planets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetOut"][];
                };
            };
        };
    };
    create_planet_api_v1_planets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planet_api_v1_planets__planet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_planet_api_v1_planets__planet_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_planet_api_v1_planets__planet_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_astronauts_api_v1_astronauts_get: {
        parameters: {
            query?: {
                /** @description Filtrer par planète */
                planet_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstronautOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_astronaut_api_v1_astronauts__astronaut_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                astronaut_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstronautOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_astronaut_profile_api_v1_astronauts__astronaut_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                astronaut_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AstronautPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstronautOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_astronaut_roles_api_v1_astronauts__astronaut_id__roles_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                astronaut_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AstronautRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstronautOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seasons_api_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"][];
                };
            };
        };
    };
    create_season_api_v1_seasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_season_api_v1_seasons_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"] | null;
                };
            };
        };
    };
    activate_season_api_v1_seasons__season_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_season_api_v1_seasons__season_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_v1_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"][];
                };
            };
        };
    };
    create_activity_api_v1_activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_v1_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_activity_api_v1_activities__activity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grades_api_v1_grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeOut"][];
                };
            };
        };
    };
    create_grade_api_v1_grades_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_grade_api_v1_grades__grade_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grade_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_grade_api_v1_grades__grade_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grade_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attributions_api_v1_point_attributions_get: {
        parameters: {
            query?: {
                planet_id?: number | null;
                astronaut_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointAttributionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attribution_api_v1_point_attributions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointAttributionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointAttributionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attribution_api_v1_point_attributions__attribution_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attribution_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointAttributionDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointAttributionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
