"""add_trophies_and_trophy_attributions

Revision ID: 5188b4636b70
Revises: ff6ba0d95579
Create Date: 2026-04-14 11:41:19.289971

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5188b4636b70'
down_revision: str | None = 'ff6ba0d95579'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trophies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('rule_config', sa.Text(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trophies_season_id'), 'trophies', ['season_id'], unique=False)
    op.create_table('trophy_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trophy_id', sa.Integer(), nullable=False),
    sa.Column('astronaut_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('awarded_by', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(astronaut_id IS NULL) != (planet_id IS NULL)', name='ck_trophy_attribution_target'),
    sa.ForeignKeyConstraint(['astronaut_id'], ['astronauts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['awarded_by'], ['astronauts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trophy_id'], ['trophies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trophy_attributions_astronaut_id'), 'trophy_attributions', ['astronaut_id'], unique=False)
    op.create_index(op.f('ix_trophy_attributions_planet_id'), 'trophy_attributions', ['planet_id'], unique=False)
    op.create_index(op.f('ix_trophy_attributions_season_id'), 'trophy_attributions', ['season_id'], unique=False)
    op.create_index(op.f('ix_trophy_attributions_trophy_id'), 'trophy_attributions', ['trophy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trophy_attributions_trophy_id'), table_name='trophy_attributions')
    op.drop_index(op.f('ix_trophy_attributions_season_id'), table_name='trophy_attributions')
    op.drop_index(op.f('ix_trophy_attributions_planet_id'), table_name='trophy_attributions')
    op.drop_index(op.f('ix_trophy_attributions_astronaut_id'), table_name='trophy_attributions')
    op.drop_table('trophy_attributions')
    op.drop_index(op.f('ix_trophies_season_id'), table_name='trophies')
    op.drop_table('trophies')
    # ### end Alembic commands ###
