"""sync astronaut email unique index and remove planet fk

Revision ID: ff6ba0d95579
Revises: 001
Create Date: 2026-04-13 09:47:31.636131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6ba0d95579'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('astronauts_email_key'), 'astronauts', type_='unique')
    op.drop_index(op.f('ix_astronauts_email'), table_name='astronauts')
    op.create_index(op.f('ix_astronauts_email'), 'astronauts', ['email'], unique=True)
    op.drop_constraint(op.f('astronauts_planet_id_fkey'), 'astronauts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('astronauts_planet_id_fkey'), 'astronauts', 'planets', ['planet_id'], ['id'])
    op.drop_index(op.f('ix_astronauts_email'), table_name='astronauts')
    op.create_index(op.f('ix_astronauts_email'), 'astronauts', ['email'], unique=False)
    op.create_unique_constraint(op.f('astronauts_email_key'), 'astronauts', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
